graphcut.o: ../src/graphcut.cpp ../src/graph.cpp ../src/LinkedBlockList.cpp ../src/maxflow.cpp ../src/GCoptimization.cpp 
	gcc -g -shared -I/usr/include/opencv ../src/*.cpp -L /usr/lib/libcv.so:/usr/lib/libhighgui.so -o graphcut
