graphcut.o: ../src/graphcut.cpp ../src/graph.cpp ../src/LinkedBlockList.cpp ../src/maxflow.cpp ../src/GCoptimization.cpp 
	gcc -fPIC -g -I/usr/include/opencv ../src/*.cpp -L/usr/lib -lml -lcv -lhighgui -o graphcut
